server:
  port: 9091
  http2:
    enabled: true


spring:
  webflux:
    base-path:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: test1
      password: test1
      database: test
      authentication-database: test
      #uri: mongodb://test:test@localhost:270
  kafka:
    bootstrap-servers: localhost:29092


logging:
  level:
    org:
      springframework:
        data:
          ## mongodb query logging
          mongodb:
            core:
              MongoTemplate: DEBUG