server:
  port: 9091
  http2:
    enabled: true
  first:
    api-token: c276558aab1cb2462c613aeca8a61301d20a0cff12e0717c3e5698b5396ae044caf72678ed3f59c7f5ab58605ec9def97f886cbb1107853c4ddadee5c7f32a9c
    host: http://localhost:8989


spring:
  webflux:
    base-path:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: test1
      password: test1
      database: test
      authentication-database: test
      #uri: mongodb://test:test@localhost:270
#      auto-index-creation: true
#      repositories:
#        type: reactive
  kafka:
    bootstrap-servers: localhost:29092


logging:
  level:
    org:
      springframework:
        data:
          # mongodb query logging
          mongodb:
            core:
#              MongoTemplate: DEBUG
              ReactiveMongoTemplate: DEBUG

